class AppString {
  static String appname = "SMedical",
      bestDocapp = "Best Doctor\n Appointment App",
      welcome = "Hoşgeldiniz ",
      weAreExcuited = "Sizi tekrar aramızda görmek bizi mutlu ediyor.",
      signupNow = "Şimdi kaydolun ve tüm olanakları keşfetmeye başlayın.",
      email = "Email",
      emailHint = "E-postanızı girin.",
      password = "Şifre",
      passwordHint = "Şifrenizi girin.",
      fullName = "Adınız ve soyadınız",
      fullnameHint = "Adınızı ve soyadınızı giriniz.",
      confirmPassword = "Şifreyi doğrulayın",
      login = "Giriş",
      signup = "Kayıt",
      search = "Doktor ara",
      alreadyHaveAccount = "Zaten hesabınız var!",
      body = "Body",
      ear = "Ear",
      liver = "Liver",
      lungs = "Lungs",
      heart = "Heart",
      kidny = "Kidny",
      eye = "Eye",
      stomac = "Stomac",
      tooth = "Tooth",
      dontHaveAccount = "Hesabınız yok mu?";
}
