// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOCmiE4uSD_INHSrRoD9s6PsdqiLItt5o',
    appId: '1:829737094806:web:ba7f6c93eaef148ecc7cb7',
    messagingSenderId: '829737094806',
    projectId: 'smedical-17baf',
    authDomain: 'smedical-17baf.firebaseapp.com',
    storageBucket: 'smedical-17baf.appspot.com',
    measurementId: 'G-9P7BQ7EQ5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGNZr6rsN9sBIQYANU9HbXCemPlhB4EM8',
    appId: '1:829737094806:android:6a9a4e7972077218cc7cb7',
    messagingSenderId: '829737094806',
    projectId: 'smedical-17baf',
    storageBucket: 'smedical-17baf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ztgXnU6_o48RSa4hpTBhMjZPw4X-RtI',
    appId: '1:829737094806:ios:20cd3ac8e253e7aacc7cb7',
    messagingSenderId: '829737094806',
    projectId: 'smedical-17baf',
    storageBucket: 'smedical-17baf.appspot.com',
    iosBundleId: 'com.example.sMedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ztgXnU6_o48RSa4hpTBhMjZPw4X-RtI',
    appId: '1:829737094806:ios:bc0c527aaaac36b1cc7cb7',
    messagingSenderId: '829737094806',
    projectId: 'smedical-17baf',
    storageBucket: 'smedical-17baf.appspot.com',
    iosBundleId: 'com.example.sMedi.RunnerTests',
  );
}
